development:
  adapter: mysql2
  database: twitter
  username: root
  host: localhost

test:
  adapter: mysql2
  database: twitter
  username: root
  host: localhost

production:
  adapter: mysql2
  database: twitter
  username: root
  host: localhost

